export const news = [
    {
        _id: '1',
        title: 'Senate Committee on Finance: Reviewing Fiscal Policy',
        content: '<p>Hon. Suleiman Kwari, as the Chairman of the Senate Committee on Finance, led a crucial session reviewing the national fiscal policy framework. The discussion focused on ensuring economic stability, reducing inflation, and creating a favorable environment for foreign investment. Hon. Kwari emphasized the need for transparency in government spending and the importance of fiscal discipline.</p>',
        category: 'Legislative',
        imageUrl: '/assets/news-fiscal-senate.jpg',
        publishDate: '2023-01-15T10:00:00Z',
        excerpt: 'Hon. Suleiman Kwari leads discussions on the new fiscal policy to ensure economic stability.',
    },
    {
        _id: '2',
        title: 'Empowering Kaduna North: Scholarship Distribution',
        content: '<p>In a bid to support education and human capital development, Hon. Suleiman Kwari distributed scholarships to over 500 indigent students from Kaduna North Senatorial District. The scholarships cover tuition fees for students in tertiary institutions. Speaking at the event, Hon. Kwari reiterated his commitment to ensuring that financial constraints do not hinder any child from accessing quality education.</p>',
        category: 'Education',
        imageUrl: '/assets/news-scholarship.jpg',
        publishDate: '2022-11-20T09:30:00Z',
        excerpt: 'Over 500 students received scholarships to pursue higher education in various fields.',
    },
    {
        _id: '3',
        title: 'Commissioning of Solar Boreholes in Zaria',
        content: '<p>To address the water scarcity challenge in some communities, Hon. Suleiman Kwari commissioned five new solar-powered boreholes in Zaria Local Government Area. The project is part of his constituency intervention aimed at providing clean and potable water to the grassroots. Residents expressed their gratitude, noting that the project would significantly improve their quality of life.</p>',
        category: 'Infrastructure',
        imageUrl: '/assets/news-borehole-zaria.jpg',
        publishDate: '2022-09-10T14:00:00Z',
        excerpt: 'Providing clean drinking water to remote communities through solar-powered boreholes.',
    },

    {
        _id: '6',
        title: 'Palliative Distribution to Vulnerable Households',
        content: '<p>To cushion the effect of economic hardship, Hon. Suleiman Kwari distributed truckloads of foodstuff including rice, maize, and millet to thousands of vulnerable households, widows, and orphans across the constituency. This gesture is part of his continuous effort to support the needy.</p>',
        category: 'Social Welfare',
        imageUrl: '/foodstup.jpg',
        publishDate: '2023-04-15T10:00:00Z',
        excerpt: 'Distribution of food items to support widows, orphans, and vulnerable families.',
    },
    {
        _id: '7',
        title: 'Support for Religious Institutions',
        content: '<p>Hon. Suleiman Kwari has extended support to various religious institutions, including the renovation of mosques and support for Islamiyya schools. This initiative aims to foster spiritual growth and community cohesion within the senatorial district.</p>',
        category: 'Community Engagement',
        imageUrl: '/addini.jpg',
        publishDate: '2023-03-20T14:30:00Z',
        excerpt: 'Supporting spiritual growth through the renovation of mosques and aid to religious schools.',
    },
    {
        _id: '8',
        title: 'Youth Empowerment Scheme',
        content: '<p>As part of his youth empowerment agenda, Hon. Kwari distributed motorcycles to unemployed youths to use for commercial transport (Okada) and logistics businesses. This initiative is designed to foster self-reliance and reduce youth unemployment in the region.</p>',
        category: 'Empowerment',
        imageUrl: '/motorcyclesempowerments.jpg',
        publishDate: '2023-02-10T11:00:00Z',
        excerpt: 'Empowering youth with motorcycles to start logistics and transport businesses.',
    },
    {
        _id: '9',
        title: 'Support for People Living with Disabilities',
        content: '<p>Hon. Suleiman Kwari distributed empowerment funds and specialized equipment to People Living with Disabilities (PWDs) in Kaduna North. The program aims to promote inclusivity and support the economic independence of physically challenged members of the community.</p>',
        category: 'Social Welfare',
        imageUrl: '/assets/news-pwd-empowerment.jpg',
        publishDate: '2022-12-05T10:00:00Z',
        excerpt: 'Empowerment funds and equipment distributed to support PWDs.',
    },
    {
        _id: '10',
        title: 'Youth Skills Acquisition & Training',
        content: '<p>Over 200 youths participated in a skills acquisition workshop sponsored by Hon. Suleiman Kwari. The training covered digital skills, carpentry, and tailoring, providing participants with the tools and knowledge to become self-employed and contributors to the local economy.</p>',
        category: 'Education',
        imageUrl: '/assets/news-youth-training.jpg',
        publishDate: '2022-02-15T09:00:00Z',
        excerpt: 'Workshop to equip youths with vocational and digital skills for self-reliance.',
    }
];
